# Generated by Django 4.2.2 on 2023-11-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meeting', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('body', models.TextField()),
            ],
        ),
    ]
